development:
  adapter: postgresql
  database: my_database_development
  username: admin
  password: 29092012
  pool: 5
  host: localhost
  encoding: UTF8
test:
  adapter: postgresql
  database: my_database_test
  username: admin
  password: 29092012
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  username: admin
  password: 29092012
  pool: 5
  timeout: 5000