development:
  adapter: postgresql
  database: my_database_development
  username: admin
  password: '29092012'
  pool: 5
  encoding: unicode
test:
  adapter: postgresql
  database: my_database_test
  username: admin
  password: '29092012'
  pool: 5
  timeout: 5000
  encoding: unicode

production:
  adapter: postgresql
  database: my_database_production
  username: admin
  password: '29092012'
  pool: 5
  timeout: 5000
  encoding: unicode
